import type { Metadata } from "next";
import "./globals.css";
import { PT_Serif } from "next/font/google";
import { HoverProvider } from "@/contexts/hoverContext";

const pt_serif = PT_Serif({
  weight: ["400", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pt_serif.className}>
        <HoverProvider>
        {children}
        </HoverProvider>
        </body>
    </html>
  );
}
